#!/usr/bin/env node

console.log("🤖 Cline OpenRouter Configuration")
console.log("==================================")
console.log()
console.log("To configure OpenRouter for the Cline CLI, you need to:")
console.log()
console.log("1. Set the following environment variables:")
console.log("   export OPENROUTER_API_KEY=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")
console.log("   export CLINE_API_PROVIDER=openrouter")
console.log("   export CLINE_MODEL_ID=deepseek/deepseek-chat-v3-0324:free")
console.log()
console.log("2. Or add them to your shell profile (~/.bashrc, ~/.zshrc, etc.):")
console.log(
	"   echo 'export OPENROUTER_API_KEY=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' >> ~/.zshrc",
)
console.log("   echo 'export CLINE_API_PROVIDER=openrouter' >> ~/.zshrc")
console.log("   echo 'export CLINE_MODEL_ID=deepseek/deepseek-chat-v3-0324:free' >> ~/.zshrc")
console.log()
console.log("3. Then restart your terminal or run:")
console.log("   source ~/.zshrc")
console.log()
console.log("4. Start the standalone server:")
console.log("   npm run standalone-simple")
console.log()
console.log("5. In another terminal, run the CLI:")
console.log("   npm run cli")
console.log()
console.log("The CLI should now work with OpenRouter!")
console.log()
console.log("Note: The standalone server will automatically pick up these environment variables")
console.log("and configure the API provider accordingly.")
